[build]
  command = "bundle exec middleman build --verbose"
  publish = "build"
  timeout = "30m"

[build.environment]
  RUBY_VERSION = "3.2.4"
  NODE_VERSION = "20.19.0"
  BUNDLE_WITHOUT = "development test"

[[edge_functions]]
  function = "protect-project"
  path = "/projects/augeo"

[[edge_functions]]
  function = "protect-project"
  path = "/projects/augeo/"
